### ISSUE TITLE
interviews

### ISSUE THREAD

**Issue by AntoanRusinov** [EvaRusinova/email-service#11]

**Comment by AntoanRusinov** [comment]
what is the difference between SDK, JDK, and JVM? What is bytecode?

**Comment by AntoanRusinov** [comment]
Database partision tolerance;
Acid Properties;
Potent methods in restful APIs;
Rest N1+ problems;

**Comment by AntoanRusinov** [comment]
Actuator: https://www.baeldung.com/spring-boot-actuators 

see endpoints and what they are used for! Basically, actuator is a health check library for our app

**Comment by AntoanRusinov** [comment]
CAP theorem - I will expect explanation :D

**Comment by AntoanRusinov** [comment]
Postman overview;
Docker+ containers, overview and explanation

**Comment by EvaRusinova** [comment]
- [ ] Beans;
- [ ] MVC;
- [ ] Java OOP;
- [ ] Java threads;
- [ ] String Buffer, StringBuilder;
- [ ] SQL, relational/non-relational database examples;
- [ ] GitHub actions;
- [ ] Spring opinion;
